import product1 from "../../images/product-1.jpg";
import product2 from "../../images/product-2.jpg";
import product3 from "../../images/product-3.jpg";
import sweet1 from "../../images/sweet1.jpg";
import sweet2 from "../../images/sweet2.jpg";
import sweet3 from "../../images/sweet3.jpg";
import sweet4 from "../../images/sweet-1.jpg";
import sweet5 from "../../images/sweet-2.jpg";
import sweet6 from "../../images/sweet-3.jpg";
import featureSweet from "../../images/sweet-4.jpg";
import featurePizza from "../../images/featured3.jpg";
import coffee1 from "../../images/coffee1.png"
import coffee2 from "../../images/coffee2.png"
import coffee3 from "../../images/coffee3.png"
import coffee4 from "../../images/coffee4.jpeg"
import coffee5 from "../../images/coffee5.jpeg"




const initialState = {
  products: [
    {
      img: coffee1,
      alt: "coffee",
      name: "Cappuccino",
      desc: "Characterized by its equal parts of espresso, steamed milk, and velvety foam",
      price: 120.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 120.00 - (4 / 100) * 120.00,
      quantity: 10,
      id: 1,
    },
    {
      img: coffee2,
      alt: "coffee",
      name: "Latte",
      desc: " the latte combines espresso with a generous amount of steamed milk, resulting in a creamy, comforting beverage",
      price: 110.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 110.00 - (4 / 100) * 110.00,
      quantity: 10,
      id: 2,
    },
    {
      img: coffee3,
      alt: "coffee",
      name: "Mocha",
      desc: "delectable fusion of espresso, steaming milk, and delicious chocolate syrup to satisfy your sweet taste",
      price: 134.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 134.00 - (4 / 100) * 134.00,
      quantity: 10,
      id: 3,
    },
    {
      img: coffee4,
      alt: "coffee",
      name: "Espresso",
      desc: "Brewed by pushing hot water through finely-ground coffee beans",
      price: 120.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 120.00 - (4 / 100) * 120.00,
      quantity: 10,
      id: 4,
    },
    {
      img: coffee5,
      alt: "coffee",
      name: "Macchiato",
      desc: "balance of espresso and milk in the macchiato, a different coffee style where a shot of espresso is “stained” with just a dollop of frothy milk. ",
      price: 99.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 99.00 - (4 / 100) * 99.00,
      quantity: 10,
      id: 5,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 299.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 299.00 - (4 / 100) * 299.00,
      quantity: 10,
      id: 6,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 234.00,
      button: "Add to Cart",
      discount: 7,
      discountPrice: 234.00 - (7 / 100) * 234.00,
      quantity: 10,
      id: 7,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 210.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 210.00 - (10 / 100) * 210.00,
      quantity: 10,
      id: 8,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 256.00,
      button: "Add to Cart",
      discount: 11,
      discountPrice: 256.00 - (11 / 100) * 256.00,
      quantity: 10,
      id: 9,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 250.00,
      button: "Add to Cart",
      discount: 12,
      discountPrice: 250.00 - (12 / 100) * 250.00,
      quantity: 10,
      id: 10,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 205.00,
      button: "Add to Cart",
      discount: 13,
      discountPrice: 205.00 - (13 / 100) * 205.00,
      quantity: 10,
      id: 11,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 189.00,
      button: "Add to Cart",
      discount: 11,
      discountPrice: 189.00 - (11 / 100) * 189.00,
      quantity: 10,
      id: 12,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 278.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 278.00 - (22 / 100) * 278.00,
      quantity: 10,
      id: 13,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 269.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 269.00 - (22 / 100) * 269.00,
      quantity: 10,
      id: 14,
    },
    {
      img: featurePizza,
      alt: "Pizza",
      name: "Truffle alfredo sauce",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 278.00,
      button: "Add to Cart",
      discount: 24,
      discountPrice: 278.00 - (24 / 100) * 278.00,
      quantity: 10,
      id: 15,
    },
   
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 215.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 215.00 - (4 / 100) * 215.00,
      quantity: 10,
      id: 16,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 215.00,
      button: "Add to Cart",
      discount: 7,
      discountPrice: 215.00 - (7 / 100) * 215.00,
      quantity: 10,
      id: 17,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 289.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 289.00 - (10 / 100) * 289.00,
      quantity: 10,
      id: 18,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 246.00,
      button: "Add to Cart",
      discount: 11,
      discountPrice: 246.00 - (11 / 100) * 246.00,
      quantity: 10,
      id: 19,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 220.00,
      button: "Add to Cart",
      discount: 12,
      discountPrice: 220.00 - (12 / 100) * 220.00,
      quantity: 10,
      id: 20,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 220.00,
      button: "Add to Cart",
      discount: 13,
      discountPrice: 220.00 - (13 / 100) * 220.00,
      quantity: 10,
      id: 21,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 215.00,
      button: "Add to Cart",
      discount: 11,
      discountPrice: 215.00 - (11 / 100) * 215.00,
      quantity: 10,
      id: 22,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 215.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 215.00 - (22 / 100) * 215.00,
      quantity: 10,
      id: 23,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 238.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 238.00 - (22 / 100) * 238.00,
      quantity: 10,
      id: 24,
    },
    {
      img: featurePizza,
      alt: "Pizza",
      name: "Truffle alfredo sauce",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 290.00,
      button: "Add to Cart",
      discount: 24,
      discountPrice: 290.00 - (24 / 100) * 290.00,
      quantity: 10,
      id: 25,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 245.00,
      button: "Add to Cart",
      discount: 12,
      discountPrice: 245.00 - (12 / 100) * 245.00,
      quantity: 10,
      id: 26,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 267.00,
      button: "Add to Cart",
      discount: 13,
      discountPrice: 267.00 - (13 / 100) * 267.00,
      quantity: 10,
      id: 27,
    },
    {
      img: featurePizza,
      alt: "Pizza",
      name: "Truffle alfredo sauce",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 234.00,
      button: "Add to Cart",
      discount: 24,
      discountPrice: 234.00 - (24 / 100) * 234.00,
      quantity: 10,
      id: 28,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 289.00,
      button: "Add to Cart",
      discount: 4,
      discountPrice: 289.00 - (4 / 100) * 289.00,
      quantity: 10,
      id: 29,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 213.00,
      button: "Add to Cart",
      discount: 7,
      discountPrice: 213.00 - (7 / 100) * 213.00,
      quantity: 10,
      id: 30,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 211.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 211.00 - (10 / 100) * 211.00,
      quantity: 10,
      id: 31,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 278.00,
      button: "Add to Cart",
      discount: 11,
      discountPrice: 278.00 - (11 / 100) * 278.00,
      quantity: 10,
      id: 32,
    },
    {
      img: product2,
      alt: "Pizza",
      name: "Hawaiian Paradise",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 278.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 278.00 - (22 / 100) * 278.00,
      quantity: 10,
      id: 33,
    },
    {
      img: product3,
      alt: "Pizza",
      name: "Veggie Overload",
      desc: " Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 278.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 278.00 - (22 / 100) * 278.00,
      quantity: 10,
      id: 34,
    },
    {
      img: product1,
      alt: "Pizza",
      name: "Supreme Pizza",
      desc: "Marinara sauce, basil, italian sausage, roma tomatoes, olives, and pesto",
      price: 219.00,
      button: "Add to Cart",
      discount: 11,
      discountPrice: 219.00 - (11 / 100) * 219.00,
      quantity: 10,
      id: 35,
    },
   
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 35.00,
      button: "Add to Cart",
      discount: 14,
      discountPrice: 35.00 - (14 / 100) * 35.00,
      quantity: 10,
      id: 36,
    },
    {
      img: featureSweet,
      alt: "cheese",
      name: "chesse cupcakes",
      desc: "Belgian chocolate cream cheese cupcakes covered in icing with sprinkles on top",
      price: 45.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 45.00 - (20 / 100) * 45.00,
      quantity: 10,
      id: 37,
    },
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 39.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 39.00 - (10 / 100) * 39.00,
      quantity: 10,
      id: 38,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 110.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 110.00 - (10 / 100) * 110.00,
      quantity: 10,
      id: 39,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 110.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 110.00 - (10 / 100) * 110.00,
      quantity: 10,
      id: 40,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 39.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 39.00 - (10 / 100) * 39.00,
      quantity: 10,
      id: 41,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 112.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 112.00 - (10 / 100) * 112.00,
      quantity: 10,
      id: 42,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 119.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 119.00 - (10 / 100) * 119.00,
      quantity: 10,
      id: 43,
    },
   
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 14,
      discountPrice: 59.00 - (14 / 100) * 59.00,
      quantity: 10,
      id: 44,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 112.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 112.00 - (20 / 100) * 112.00,
      quantity: 10,
      id: 45,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 119.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 119.00 - (20 / 100) * 119.00,
      quantity: 10,
      id: 46,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 69.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 69.00 - (22 / 100) * 69.00,
      quantity: 10,
      id: 47,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 21,
      discountPrice: 132.00 - (21 / 100) * 132.00,
      quantity: 10,
      id: 48,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 142.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 142.00 - (22 / 100) * 142.00,
      quantity: 10,
      id: 49,
    },
   
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 23,
      discountPrice: 59.00 - (23 / 100) * 59.00,
      quantity: 10,
      id: 50,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 132.00 - (25 / 100) * 132.00,
      quantity: 10,
      id: 51,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 159.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 159.00 - (25 / 100) * 159.00,
      quantity: 10,
      id: 52,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 59.00 - (25 / 100) * 59.00,
      quantity: 10,
      id: 53,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 132.00 - (25 / 100) * 132.00,
      quantity: 10,
      id: 54,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 132.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 132.00 - (25 / 100) * 132.00,
      quantity: 10,
      id: 55,
    },
   
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 59.00 - (10 / 100) * 59.00,
      quantity: 10,
      id: 56,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 142.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 142.00 - (10 / 100) * 142.00,
      quantity: 10,
      id: 57,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 149.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 149.00 - (10 / 100) * 149.00,
      quantity: 10,
      id: 58,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 59.00 - (10 / 100) * 59.00,
      quantity: 10,
      id: 59,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 112.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 112.00 - (10 / 100) * 112.00,
      quantity: 10,
      id: 60,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 59.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 59.00 - (10 / 100) * 59.00,
      quantity: 10,
      id: 61,
    },
   
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 14,
      discountPrice: 59.00 - (14 / 100) * 59.00,
      quantity: 10,
      id: 62,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 132.00 - (20 / 100) * 132.00,
      quantity: 10,
      id: 63,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 119.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 119.00 - (20 / 100) * 119.00,
      quantity: 10,
      id: 64,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 59.00 - (22 / 100) * 59.00,
      quantity: 10,
      id: 65,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 21,
      discountPrice: 132.00 - (21 / 100) * 132.00,
      quantity: 10,
      id: 66,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 129.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 129.00 - (22 / 100) * 129.00,
      quantity: 10,
      id: 67,
    },
    
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 23,
      discountPrice: 59.00 - (23 / 100) * 59.00,
      quantity: 10,
      id: 68,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 132.00 - (25 / 100) * 132.00,
      quantity: 10,
      id: 69,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 59.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 59.00 - (25 / 100) * 59.00,
      quantity: 10,
      id: 70,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 59.00 - (25 / 100) * 59.00,
      quantity: 10,
      id: 71,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 142.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 142.00 - (25 / 100) * 142.00,
      quantity: 10,
      id: 72,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 119.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 119.00 - (25 / 100) * 119.00,
      quantity: 10,
      id: 73,
    },
   
    {
      img: featureSweet,
      alt: "cheese",
      name: "chesse cupcakes",
      desc: "Belgian chocolate cream cheese cupcakes covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 59.00 - (20 / 100) * 59.00,
      quantity: 10,
      id: 74,
    },
   
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 59.00 - (10 / 100) * 59.00,
      quantity: 10,
      id: 75,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 142.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 142.00 - (10 / 100) * 142.00,
      quantity: 10,
      id: 76,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 129.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 129.00 - (10 / 100) * 129.00,
      quantity: 10,
      id: 77,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 59.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 59.00 - (10 / 100) * 59.00,
      quantity: 10,
      id: 78,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 132.00 - (10 / 100) * 132.00,
      quantity: 10,
      id: 79,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 129.00,
      button: "Add to Cart",
      discount: 10,
      discountPrice: 129.00 - (10 / 100) * 129.00,
      quantity: 10,
      id: 80,
    },
    
  
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 122.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 122.00 - (20 / 100) * 122.00,
      quantity: 10,
      id: 81,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 69.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 69.00 - (20 / 100) * 69.00,
      quantity: 10,
      id: 82,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 69.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 69.00 - (22 / 100) * 69.00,
      quantity: 10,
      id: 83,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 132.00,
      button: "Add to Cart",
      discount: 21,
      discountPrice: 132.00 - (21 / 100) * 132.00,
      quantity: 10,
      id: 84,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 49.00,
      button: "Add to Cart",
      discount: 22,
      discountPrice: 49.00 - (22 / 100) * 49.00,
      quantity: 10,
      id: 85,
    },
   
    
    {
      img: sweet2,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 69.00,
      button: "Add to Cart",
      discount: 23,
      discountPrice: 69.00 - (23 / 100) * 69.00,
      quantity: 10,
      id: 86,
    },
    {
      img: sweet3,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 122.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 122.00 - (25 / 100) * 122.00,
      quantity: 10,
      id: 87,
    },
    {
      img: sweet1,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 69.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 69.00 - (25 / 100) * 69.00,
      quantity: 10,
      id: 88,
    },
    {
      img: sweet4,
      alt: "Donuts",
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top",
      price: 69.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 69.00 - (25 / 100) * 69.00,
      quantity: 10,
      id: 89,
    },
    {
      img: sweet5,
      alt: "Ice Cream",
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick",
      price: 142.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 142.00 - (25 / 100) * 142.00,
      quantity: 10,
      id: 90,
    },
    {
      img: sweet6,
      alt: "Brownie",
      name: "Brownie Bunch",
      desc: "Double fudge brownie squares topped with white chocolate pieces and macadamia nuts",
      price: 169.00,
      button: "Add to Cart",
      discount: 25,
      discountPrice: 169.00 - (25 / 100) * 169.00,
      quantity: 10,
      id: 91,
    },
    
    {
      img: featureSweet,
      alt: "cheese",
      name: "chesse cupcakes",
      desc: "Belgian chocolate cream cheese cupcakes covered in icing with sprinkles on top",
      price: 69.00,
      button: "Add to Cart",
      discount: 20,
      discountPrice: 69.00 - (20 / 100) * 69.00,
      quantity: 10,
      id: 92,
    },
  ],
  product: {},
};

const ProductsReducer = (state = initialState, action) => {
  switch (action.type) {
    case "PRODUCT":
      return {
        ...state,
        product: state.products.find(
          (product) => product.id === parseInt(action.id)
        ),
      };
    default:
      return state;
  }
};

export default ProductsReducer;
